// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tasks_lib/domain/models.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<void> syncDb({required String dbPath}) =>
    RustLib.instance.api.crateApiSimpleSyncDb(dbPath: dbPath);

Future<List<Task>> getAllTasks() =>
    RustLib.instance.api.crateApiSimpleGetAllTasks();

Future<void> deleteTask({required int id}) =>
    RustLib.instance.api.crateApiSimpleDeleteTask(id: id);

Future<void> createTask({
  required int id,
  required String title,
  required String description,
  required bool completed,
}) => RustLib.instance.api.crateApiSimpleCreateTask(
  id: id,
  title: title,
  description: description,
  completed: completed,
);

Future<void> updateTask({
  required int id,
  required String title,
  required String description,
  required bool completed,
}) => RustLib.instance.api.crateApiSimpleUpdateTask(
  id: id,
  title: title,
  description: description,
  completed: completed,
);
