// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<List<Task>> getAllTasks() =>
    RustLib.instance.api.crateApiSimpleGetAllTasks();

Future<void> deleteTask({required int id}) =>
    RustLib.instance.api.crateApiSimpleDeleteTask(id: id);

Future<void> createTask({
  required int id,
  required String title,
  required String description,
  required bool completed,
}) => RustLib.instance.api.crateApiSimpleCreateTask(
  id: id,
  title: title,
  description: description,
  completed: completed,
);

Future<void> updateTask({
  required int id,
  required String title,
  required String description,
  required bool completed,
}) => RustLib.instance.api.crateApiSimpleUpdateTask(
  id: id,
  title: title,
  description: description,
  completed: completed,
);

class Task {
  final int id;
  final String title;
  final String description;
  final bool completed;

  const Task({
    required this.id,
    required this.title,
    required this.description,
    required this.completed,
  });

  Future<Task> copyWith({required bool completed}) => RustLib.instance.api
      .crateApiSimpleTaskCopyWith(that: this, completed: completed);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Task> newInstance({
    required int id,
    required String title,
    required String description,
    required bool completed,
  }) => RustLib.instance.api.crateApiSimpleTaskNew(
    id: id,
    title: title,
    description: description,
    completed: completed,
  );

  Future<String> toJson() =>
      RustLib.instance.api.crateApiSimpleTaskToJson(that: this);

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ description.hashCode ^ completed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Task &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          description == other.description &&
          completed == other.completed;
}
