// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Task {
  final int id;
  final String title;
  final String description;
  final bool completed;

  const Task.raw({
    required this.id,
    required this.title,
    required this.description,
    required this.completed,
  });

  Future<Task> copyWith({required bool completed}) =>
      RustLib.instance.api.crateApiTasksLibDomainModelsTaskCopyWith(
        that: this,
        completed: completed,
      );

  factory Task({
    required int id,
    required String title,
    required String description,
    required bool completed,
  }) => RustLib.instance.api.crateApiTasksLibDomainModelsTaskNew(
    id: id,
    title: title,
    description: description,
    completed: completed,
  );

  Future<String> toJson() =>
      RustLib.instance.api.crateApiTasksLibDomainModelsTaskToJson(that: this);

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ description.hashCode ^ completed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Task &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          description == other.description &&
          completed == other.completed;
}
